//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artistry_WF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/Artistry_CL.classes")]
    [System.SerializableAttribute()]
    public partial class Gender : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenderID {
            get {
                return this.GenderIDField;
            }
            set {
                if ((this.GenderIDField.Equals(value) != true)) {
                    this.GenderIDField = value;
                    this.RaisePropertyChanged("GenderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IArtistryService")]
    public interface IArtistryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtistryService/GetGenderInfo", ReplyAction="http://tempuri.org/IArtistryService/GetGenderInfoResponse")]
        Artistry_WF.ServiceReference1.Gender[] GetGenderInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtistryService/GetGenderInfo", ReplyAction="http://tempuri.org/IArtistryService/GetGenderInfoResponse")]
        System.Threading.Tasks.Task<Artistry_WF.ServiceReference1.Gender[]> GetGenderInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtistryService/AddGender", ReplyAction="http://tempuri.org/IArtistryService/AddGenderResponse")]
        void AddGender(string genderDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtistryService/AddGender", ReplyAction="http://tempuri.org/IArtistryService/AddGenderResponse")]
        System.Threading.Tasks.Task AddGenderAsync(string genderDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtistryService/UpdateGender", ReplyAction="http://tempuri.org/IArtistryService/UpdateGenderResponse")]
        void UpdateGender(int id, string genderDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtistryService/UpdateGender", ReplyAction="http://tempuri.org/IArtistryService/UpdateGenderResponse")]
        System.Threading.Tasks.Task UpdateGenderAsync(int id, string genderDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtistryService/DeleteGender", ReplyAction="http://tempuri.org/IArtistryService/DeleteGenderResponse")]
        void DeleteGender(int id, string genderDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArtistryService/DeleteGender", ReplyAction="http://tempuri.org/IArtistryService/DeleteGenderResponse")]
        System.Threading.Tasks.Task DeleteGenderAsync(int id, string genderDescription);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArtistryServiceChannel : Artistry_WF.ServiceReference1.IArtistryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArtistryServiceClient : System.ServiceModel.ClientBase<Artistry_WF.ServiceReference1.IArtistryService>, Artistry_WF.ServiceReference1.IArtistryService {
        
        public ArtistryServiceClient() {
        }
        
        public ArtistryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArtistryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtistryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtistryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Artistry_WF.ServiceReference1.Gender[] GetGenderInfo() {
            return base.Channel.GetGenderInfo();
        }
        
        public System.Threading.Tasks.Task<Artistry_WF.ServiceReference1.Gender[]> GetGenderInfoAsync() {
            return base.Channel.GetGenderInfoAsync();
        }
        
        public void AddGender(string genderDescription) {
            base.Channel.AddGender(genderDescription);
        }
        
        public System.Threading.Tasks.Task AddGenderAsync(string genderDescription) {
            return base.Channel.AddGenderAsync(genderDescription);
        }
        
        public void UpdateGender(int id, string genderDescription) {
            base.Channel.UpdateGender(id, genderDescription);
        }
        
        public System.Threading.Tasks.Task UpdateGenderAsync(int id, string genderDescription) {
            return base.Channel.UpdateGenderAsync(id, genderDescription);
        }
        
        public void DeleteGender(int id, string genderDescription) {
            base.Channel.DeleteGender(id, genderDescription);
        }
        
        public System.Threading.Tasks.Task DeleteGenderAsync(int id, string genderDescription) {
            return base.Channel.DeleteGenderAsync(id, genderDescription);
        }
    }
}
